spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_networks
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: ajay
    password: ajay
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimout: 5000
        timeout: 3000
        writetimeout: 5000
  thymeleaf:
    prefix:
      classpath: /templates/
    suffix=:
      .html

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account




server:
  port: 8080